apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: zercurity
  labels:
    app: zercurity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      containers:
        - name: backend
          image: ghcr.io/zercurity/workers:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: config
          - secretRef:
              name: secrets
          volumeMounts:
          - name: nfs
            readOnly: true
            mountPath: /var/task/run/libs/resources/certs
            subPath: certs

