apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: zercurity
  labels:
    vendor: zercurity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
