apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: zercurity
type: Opaque
data:
# These are base64 encoded values. The original values can be found in the cm-config.yaml
# This is an example and should be changed.
  SECRET: UjJ1M0ZmVXBUamY4Tlk2UG41Z2FNYmttVUJxRnNaZmo
  DB_PASSWORD: emVyY3VyaXR5
